Create EnchantmentCracker_zh_tw.properties
Earthcomputer/EnchantmentCracker pull request #201
Opened 2020-09-19 11:36 UTC by whats2000

2020-09-20 09:34 UTC, Earthcomputer requested changes

2020-09-20 09:34 UTC, Earthcomputer commented on resources/i18n/EnchantmentCracker_zh_tw.properties
> +enchCalc.noDummy = 無虛設數值
Not an expert in traditional chinese, but I think this should be more along the lines of:
```suggestion
enchCalc.noDummy = 無额外個附魔
```

2020-09-20 09:34 UTC, Earthcomputer commented on resources/i18n/EnchantmentCracker_zh_tw.properties
> +program.about = Enchantment Cracker %s\n\
This section needs translating as well

2020-09-23 12:14 UTC, whats2000 commented
Sorry for sending too much comment at a same time,  the network have some issue. By the way, is this changes much better?

2020-09-23 17:16 UTC, Earthcomputer approved these changes
Looks good, thank you!

2020-09-23 17:16 UTC, merged